# Generated by Django 3.0.3 on 2020-04-22 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=50, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('gender', models.CharField(choices=[('select', 'Select'), ('male', 'Male'), ('female', 'Female')], default='select', max_length=6)),
                ('cimg', models.ImageField(blank=True, upload_to='images')),
                ('cinfo', models.CharField(max_length=15)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
