# Generated by Django 3.0.3 on 2020-04-22 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20200422_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactlist',
            name='manager',
        ),
    ]
