# Generated by Django 4.1.3 on 2022-11-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contactlist_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactlist',
            old_name='cinfo',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='contactlist',
            old_name='cimg',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='contactlist',
            old_name='phone',
            new_name='telefone',
        ),
        migrations.RemoveField(
            model_name='contactlist',
            name='gender',
        ),
        migrations.AddField(
            model_name='contactlist',
            name='genero',
            field=models.CharField(choices=[('select', 'Selecionar'), ('male', 'Male'), ('female', 'Female')], default='select', max_length=6),
        ),
    ]
