# Generated by Django 4.1.3 on 2022-11-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_rename_cinfo_contactlist_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactlist',
            old_name='name',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='genero',
            field=models.CharField(choices=[('select', 'Selecionar'), ('homem', 'Homem'), ('mulher', 'Mulher')], default='select', max_length=6),
        ),
    ]
